### PR TITLE
Add support for Python 3.7

### PR DESCRIPTION
**Pull request by michael-k**
As requested here: https://github.com/klen/pylama/pull/120#issuecomment-410406775

### CODE REVIEW

**Comment by fmv1992** [comment]
I do appreciate your help. However I feel that this plugin together with python-mode is getting quite complex and we don't have tests setup as of now. Therefore I'm disinclined to accept any PRs. I hope you understand.

I'll try to dedicate some more time to get the tests back on track for this project and then expand it to python-mode.

Marking @diraol , just to keep him up to date.

**Comment by little-dude** [comment]
@fmv1992 I'm using python-mode and my python version is 3.7, so I get the error described in https://github.com/klen/pylama/issues/123.

Since this PR fixes the issue and does not add complexity (it just renames an attribute), would you consider merging it anyway?

**Comment by diraol** [comment]
Thanks for the notice @fmv1992 ! =)
I understand your point, but I think that @little-dude has made a good point in favor or this PR.
It is not exactly python 3.7 support, it is just a small adjustment regarding python reserved keywords (that should have been done for python 3.6 I think). I see no harm in accepting this PR specifically.

**Comment by fmv1992** [comment]
I just did.

I'm sorry, I probably was overzealous about it.

edit: thanks for the contributions! : )

**Comment by little-dude** [comment]
Thanks @fmv1992, no need to be sorry about anything. Thank you for the effort you put to maintain this project, I've been using `pylama` through python-mode for years now.

**Pull request merged**
